# Homework 1: Introduction to Machine Learning

Machine Learning Zoomcamp 2026
- Fabián Bayas Moscoso

In [3]:
import pandas as pd
import numpy as np

## 1. Pandas version (1 point)

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2


In [5]:
print(pd.__version__)

2.3.3


## 2. Records count (1 point)

In [6]:
df.shape[0]

10000

## 3. Fuel types (1 point)

In [7]:
df["fuel_type"].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

## 4. Missing values (1 point)

In [8]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## 5. Max fuel efficiency (1 point)

In [9]:
df["fuel_efficiency_mpg"].nlargest(10)

6354    41.2
4077    39.8
2708    39.4
1800    39.2
2181    39.2
7860    39.2
228     39.1
5720    39.1
3883    39.0
4430    39.0
Name: fuel_efficiency_mpg, dtype: float64

## 6. Median value of horsepower (1 point)

In [12]:
# Step 1: Find the median value of horsepower column
median_before = df["horsepower"].median()
print("Median horsepower (before filling):", median_before)

# Step 2: Calculate the most frequent value of horsepower column
most_frequent_horsepower = df["horsepower"].mode()[0]
print("Most frequent horsepower value:", most_frequent_horsepower)

# Step 3: Fill missing values in horsepower with the most frequent value
df["horsepower"] = df["horsepower"].fillna(most_frequent_horsepower)

# Step 4: Calculate the median value of horsepower again
median_after = df["horsepower"].median()
print("Median horsepower (after filling):", median_after)

# Step 5: Compare the values
print("Median changed:", median_before != median_after)
if median_before != median_after:
    if median_after > median_before:
        print("Answer: Yes, it increased")
    else:
        print("Answer: Yes, it decreased")
else:
    print("Answer: No")

Median horsepower (before filling): 252.0
Most frequent horsepower value: 252.0
Median horsepower (after filling): 252.0
Median changed: False
Answer: No


## 7. Sum of weights (1 point)

In [11]:
# Step 1: Select all cars from Asia
asia_cars = df[df['origin'] == 'Asia']

# Step 2: Select only columns vehicle_weight and model_year
asia_selected = asia_cars[['vehicle_weight', 'model_year']]

# Step 3: Select the first 7 values
asia_first_7 = asia_selected.head(7)
print("First 7 cars from Asia with vehicle_weight and model_year:")
print(asia_first_7)

# Step 4: Get the underlying NumPy array
X = asia_first_7.values
print("NumPy array X:")
print(X)

# Step 5: Compute matrix-matrix multiplication: X.T @ X
XTX = X.T @ X
print("X.T @ X (XTX):")
print(XTX)

# Step 6: Invert XTX
XTX_inv = np.linalg.inv(XTX)
print("Inverse of XTX:")
print(XTX_inv)

# Step 7: Create array y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print("Array y:")
print(y)

# Step 8: Compute w = (X.T @ X)^-1 @ X.T @ y
w = XTX_inv @ X.T @ y
print("Result w:")
print(w)

# Step 9: Get the sum of all elements of w
sum_w = np.sum(w)
print("Sum of all elements in w:", sum_w)

First 7 cars from Asia with vehicle_weight and model_year:
    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019
NumPy array X:
[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
X.T @ X (XTX):
[[131950500  60750580]
 [ 60750580  28041424]]
Inverse of XTX:
[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]
Array y:
[1100 1300  800  900 1000 1100 1200]
Result w:
[0.13644777 0.2327492 ]
Sum of all elements in w: 0.36919696904925486
